import './style'
export { default as WdConfirmDialog } from './ConfirmDialog.vue'
export type { ConfirmDialogEmits, ConfirmDialogProps } from './types'
export { useConfirm } from './useConfirm'
export type { ConfirmRequireOptions } from './useConfirm'
