import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const compsDir = join(root, 'src/components')
const srcDir = join(root, 'src')

const comps = readdirSync(compsDir).filter((f) => statSync(join(compsDir, f)).isDirectory()).sort()

function toSlug(folder) {
  return folder
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-z\d])([A-Z])/g, '$1-$2')
    .toLowerCase()
}

const exportRe = /export\s+\{\s*default\s+as\s+(Wd[A-Za-z0-9]+)/g

const componentImportMap = {}
for (const folder of comps) {
  const indexPath = join(compsDir, folder, 'index.ts')
  if (!existsSync(indexPath)) continue
  const slug = toSlug(folder)
  const text = readFileSync(indexPath, 'utf8')
  let match
  while ((match = exportRe.exec(text)) !== null) {
    componentImportMap[match[1]] = slug
  }
}

const exportsEntries = [
  ['.', { types: './dist/index.d.ts', import: './dist/index.js' }],
  ['./styles.css', './dist/styles.css'],
  ['./resolver', { types: './dist/resolver.d.ts', import: './dist/resolver.js' }],
]

for (const c of comps) {
  const slug = toSlug(c)
  exportsEntries.push([
    `./${slug}`,
    {
      types: `./dist/components/${c}/index.d.ts`,
      import: `./dist/${slug}/index.js`,
    },
  ])
  exportsEntries.push([`./${slug}/style`, `./dist/${slug}/style.js`])
  exportsEntries.push([`./${slug}/style.css`, `./dist/${slug}/style.css`])
}
exportsEntries.push(['./docs', './src/docs/index.ts'])

const exportsObject = Object.fromEntries(exportsEntries)

const pkgPath = join(root, 'package.json')
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))

pkg.exports = exportsObject
pkg.sideEffects = [
  '**/*.css',
  '**/*/style.js',
  ...comps.map((c) => {
    const slug = toSlug(c)
    return `**/${slug}/index.js`
  }),
]

writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)  }\n`)

const mapLines = Object.entries(componentImportMap)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, slug]) => `  ${JSON.stringify(name)}: ${JSON.stringify(slug)},`)
  .join('\n')

writeFileSync(
  join(srcDir, 'resolver-map.ts'),
  `// Generated by scripts/generate-exports.mjs — do not edit manually.\n\nexport const componentImportMap: Record<string, string> = {\n${mapLines}\n}\n`,
)

console.log(
  `Updated package.json exports/sideEffects and resolver-map.ts for ${comps.length} components (${Object.keys(componentImportMap).length} public names).`,
)
